
name: test

run-name: '${{ github.actor }} - deploy to ${{ inputs.subscriptionName }} - ${{ inputs.resourceType }}'

on:
  workflow_dispatch:
    inputs:
      subscriptionName:
        type: string
        required: true
        default: ''
      resourceGroupName:
        type: string
        required: true
        default: ''
      resourceType:
        type: string
        required: true
        default: ''

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        id: test
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: Write GitHub context to log
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Write GitHub context to log
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
